name: Remove untagged Docker images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  remove-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Remove untagged Docker images
        uses: nationalarchives/ds-docker-actions/.github/actions/remove-untagged@main
        with:
          docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
